TrainingDataParams:  # 教師データ作成用のパラメータ
  generate_field_num: 30  # フィールドの生成数
  object_num: 7  # フィールド上のオブジェクト数
  point_num: 5  # フィールド上に配置する点の数(ここからランダムにstart/goal地点が選択される。)
  point_cloud_num: 1540  # 点群の点数(object_numの整数倍)

CAEParams:  # CAE学習用のパラメータ
  epoch_num: 70
  batch_size: 4
  latent_space_size: 32
